Update location of excutils: it moved from neutron.openstack.common to oslo.utils
This is need to avoid the following issue:

    4693 TRACE stevedore.extension from neutron.openstack.common import excutils
    4693 TRACE stevedore.extension ImportError: cannot import name excutils

That is because excutils has been removed after it graduated to a library